--
-- PostgreSQL database dump
--

-- Dumped from database version 12.13 (Ubuntu 12.13-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.13 (Ubuntu 12.13-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO nabalayo;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO nabalayo;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO nabalayo;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO nabalayo;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO nabalayo;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO nabalayo;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO nabalayo;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO nabalayo;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO nabalayo;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO nabalayo;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO nabalayo;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO nabalayo;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO nabalayo;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO nabalayo;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO nabalayo;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO nabalayo;

--
-- Name: expenses_budget; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_budget (
    id bigint NOT NULL,
    category character varying(100) NOT NULL,
    budgeted_amount numeric(10,2) NOT NULL,
    user_id integer NOT NULL,
    currency character varying(10) NOT NULL,
    alert_sent boolean NOT NULL,
    half_alert_sent boolean NOT NULL,
    date_created date NOT NULL
);


ALTER TABLE public.expenses_budget OWNER TO nabalayo;

--
-- Name: expenses_budget_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_budget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses_expensemanagement; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_expensemanagement (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    amount numeric(10,2) NOT NULL,
    category character varying(100) NOT NULL,
    date date NOT NULL,
    description text,
    user_id integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL
);


ALTER TABLE public.expenses_expensemanagement OWNER TO nabalayo;

--
-- Name: expenses_expensemanagement_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_expensemanagement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_expensemanagement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses_expensereport; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_expensereport (
    id bigint NOT NULL,
    report_date date NOT NULL,
    total_expenses numeric(10,2) NOT NULL,
    total_income numeric(10,2) NOT NULL,
    net_savings numeric(10,2) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.expenses_expensereport OWNER TO nabalayo;

--
-- Name: expenses_expensereport_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_expensereport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_expensereport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses_incomemanagement; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_incomemanagement (
    id bigint NOT NULL,
    source character varying(100) NOT NULL,
    amount numeric(10,2) NOT NULL,
    date date NOT NULL,
    description text,
    user_id integer NOT NULL,
    currency character varying(3) NOT NULL
);


ALTER TABLE public.expenses_incomemanagement OWNER TO nabalayo;

--
-- Name: expenses_incomemanagement_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_incomemanagement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_incomemanagement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses_monthlyexpensereport; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_monthlyexpensereport (
    id bigint NOT NULL,
    report_date date NOT NULL,
    total_expenses numeric(10,2) NOT NULL,
    total_income numeric(10,2) NOT NULL,
    net_savings numeric(10,2) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.expenses_monthlyexpensereport OWNER TO nabalayo;

--
-- Name: expenses_monthlyexpensereport_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_monthlyexpensereport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_monthlyexpensereport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses_userauthentication; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_userauthentication (
    id bigint NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    email character varying(254) NOT NULL
);


ALTER TABLE public.expenses_userauthentication OWNER TO nabalayo;

--
-- Name: expenses_userauthentication_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_userauthentication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_userauthentication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses_userprofile; Type: TABLE; Schema: public; Owner: nabalayo
--

CREATE TABLE public.expenses_userprofile (
    id bigint NOT NULL,
    profile_picture character varying(100),
    bio text,
    date_of_birth date,
    user_id integer NOT NULL
);


ALTER TABLE public.expenses_userprofile OWNER TO nabalayo;

--
-- Name: expenses_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: nabalayo
--

ALTER TABLE public.expenses_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add expense management	7	add_expensemanagement
26	Can change expense management	7	change_expensemanagement
27	Can delete expense management	7	delete_expensemanagement
28	Can view expense management	7	view_expensemanagement
29	Can add income management	8	add_incomemanagement
30	Can change income management	8	change_incomemanagement
31	Can delete income management	8	delete_incomemanagement
32	Can view income management	8	view_incomemanagement
33	Can add user authentication	9	add_userauthentication
34	Can change user authentication	9	change_userauthentication
35	Can delete user authentication	9	delete_userauthentication
36	Can view user authentication	9	view_userauthentication
37	Can add user profile	10	add_userprofile
38	Can change user profile	10	change_userprofile
39	Can delete user profile	10	delete_userprofile
40	Can view user profile	10	view_userprofile
41	Can add expense report	11	add_expensereport
42	Can change expense report	11	change_expensereport
43	Can delete expense report	11	delete_expensereport
44	Can view expense report	11	view_expensereport
45	Can add budget	12	add_budget
46	Can change budget	12	change_budget
47	Can delete budget	12	delete_budget
48	Can view budget	12	view_budget
49	Can add monthly expense report	13	add_monthlyexpensereport
50	Can change monthly expense report	13	change_monthlyexpensereport
51	Can delete monthly expense report	13	delete_monthlyexpensereport
52	Can view monthly expense report	13	view_monthlyexpensereport
53	Can add crontab	14	add_crontabschedule
54	Can change crontab	14	change_crontabschedule
55	Can delete crontab	14	delete_crontabschedule
56	Can view crontab	14	view_crontabschedule
57	Can add interval	15	add_intervalschedule
58	Can change interval	15	change_intervalschedule
59	Can delete interval	15	delete_intervalschedule
60	Can view interval	15	view_intervalschedule
61	Can add periodic task	16	add_periodictask
62	Can change periodic task	16	change_periodictask
63	Can delete periodic task	16	delete_periodictask
64	Can view periodic task	16	view_periodictask
65	Can add periodic task track	17	add_periodictasks
66	Can change periodic task track	17	change_periodictasks
67	Can delete periodic task track	17	delete_periodictasks
68	Can view periodic task track	17	view_periodictasks
69	Can add solar event	18	add_solarschedule
70	Can change solar event	18	change_solarschedule
71	Can delete solar event	18	delete_solarschedule
72	Can view solar event	18	view_solarschedule
73	Can add clocked	19	add_clockedschedule
74	Can change clocked	19	change_clockedschedule
75	Can delete clocked	19	delete_clockedschedule
76	Can view clocked	19	view_clockedschedule
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
7	pbkdf2_sha256$600000$EBG1ySdzTTifgFtLb9GWMk$8IRV7/ohXx4iE/RkN/xg8QXMYuFUyt3uLRIU2l6D0+Y=	2025-06-30 16:02:55.6194+03	f	First1			cecibarasa@gmail.com	f	t	2025-05-14 15:17:08.234876+03
1	pbkdf2_sha256$600000$4ov5qhiRM2G3IKsgL3tqyd$moioC7ahN/TD3oqpkhZLxSaE2h32LmI0C8sHfbLlnK0=	2025-07-08 15:07:11.441001+03	t	nabalayo				t	t	2025-04-28 19:43:22.613883+03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-04-28 19:44:05.579447+03	1	First trial - 2000	1	[{"added": {}}]	7	1
2	2025-04-28 19:56:48.965275+03	1	iddek - 20000	1	[{"added": {}}]	8	1
3	2025-04-29 12:58:05.3064+03	3	Entertainment - 3000 KES	1	[{"added": {}}]	12	1
4	2025-04-29 14:58:35.380041+03	1	iddek - 50000.00	2	[{"changed": {"fields": ["Amount"]}}]	8	1
5	2025-04-29 15:26:28.895984+03	1	First trial - 2000.00	2	[{"changed": {"fields": ["Status"]}}]	7	1
6	2025-04-29 15:30:58.358844+03	1	First trial - 2000.00	3		7	1
7	2025-04-29 18:44:35.99555+03	14	another one - 654.00	3		7	1
8	2025-04-29 18:44:37.361886+03	13	Unknown - 2650.00	3		7	1
9	2025-04-29 18:44:37.431313+03	12	Record screel - 5000.00	3		7	1
10	2025-04-29 18:44:37.617247+03	11	Record screel - 5000.00	3		7	1
11	2025-04-29 18:44:37.88515+03	10	welll - 2300.00	3		7	1
12	2025-04-29 18:44:38.021355+03	9	welll - 2300.00	3		7	1
13	2025-04-29 18:44:38.12687+03	8	harikan dragon - 6000.00	3		7	1
14	2025-04-29 18:44:38.195986+03	7	Testing - 5899.00	3		7	1
15	2025-04-29 18:44:38.428932+03	6	salary - 2650.00	3		7	1
16	2025-04-29 18:44:38.552628+03	5	salary - 2650.00	3		7	1
17	2025-04-29 18:44:38.593035+03	4	salary - 2650.00	3		7	1
18	2025-04-29 20:39:46.47569+03	1	Monthly Report for nabalayo on 2025-04-29	1	[{"added": {}}]	13	1
19	2025-04-30 12:41:06.592906+03	16	Wednesday - 200	1	[{"added": {}}]	7	1
20	2025-04-30 12:42:21.643562+03	15	another one - 654.00	2	[{"changed": {"fields": ["User", "Category", "Status"]}}]	7	1
21	2025-04-30 13:27:20.603894+03	15	another one - 1054.00	2	[{"changed": {"fields": ["Amount"]}}]	7	1
22	2025-04-30 13:30:27.29838+03	17	Battery - 3000.00	2	[{"changed": {"fields": ["User", "Category"]}}]	7	1
23	2025-04-30 14:27:33.150526+03	18	phone - 30000.00	2	[{"changed": {"fields": ["User", "Category", "Status"]}}]	7	1
24	2025-04-30 14:27:42.818773+03	17	Battery - 3000.00	2	[{"changed": {"fields": ["Status"]}}]	7	1
25	2025-04-30 14:33:13.716929+03	18	phone - 30000.00	3		7	1
26	2025-04-30 14:33:14.043685+03	17	Battery - 3000.00	3		7	1
27	2025-04-30 14:33:14.926747+03	16	Wednesday - 200.00	3		7	1
28	2025-04-30 14:33:15.263337+03	15	another one - 1054.00	3		7	1
29	2025-04-30 14:34:25.750818+03	19	phone - 30000.00	2	[{"changed": {"fields": ["User", "Category"]}}]	7	1
30	2025-04-30 15:11:52.781107+03	23	Testing - 10.00	3		7	1
31	2025-04-30 15:11:52.990905+03	22	Testing - 20.00	3		7	1
32	2025-04-30 15:11:53.051247+03	21	Testing - 20.00	3		7	1
33	2025-04-30 15:11:53.191413+03	20	phone - 30000.00	3		7	1
34	2025-04-30 15:11:53.255844+03	19	phone - 30000.00	3		7	1
35	2025-04-30 15:14:34.613596+03	24	Testing - 10.00	2	[{"changed": {"fields": ["User", "Category", "Status"]}}]	7	1
36	2025-04-30 15:20:17.043295+03	25	TestingSS - 20.00	2	[{"changed": {"fields": ["User", "Category", "Status"]}}]	7	1
37	2025-04-30 15:26:16.082305+03	27	salary - 33000.00	2	[{"changed": {"fields": ["User", "Category", "Status"]}}]	7	1
38	2025-04-30 15:45:41.781265+03	28	LAST - 10000.00	2	[{"changed": {"fields": ["User", "Category", "Status"]}}]	7	1
39	2025-05-05 11:12:00.648905+03	31	Shoes - 1800.00	2	[{"changed": {"fields": ["User"]}}]	7	1
40	2025-05-05 14:12:54.828132+03	36	Battery - 2000.00	3		7	1
41	2025-05-05 14:12:55.416948+03	35	Heels - 3000.00	3		7	1
42	2025-05-05 14:12:55.616654+03	30	welll - 5000.00	3		7	1
43	2025-05-05 14:12:55.692681+03	29	LAST - 10000.00	3		7	1
44	2025-05-05 14:12:55.828833+03	28	LAST - 10000.00	3		7	1
45	2025-05-05 14:12:55.893598+03	27	salary - 33000.00	3		7	1
46	2025-05-05 14:12:55.951331+03	26	salary - 33000.00	3		7	1
47	2025-05-05 14:13:15.886614+03	3	Entertainment - 3000.00 KES	3		12	1
48	2025-05-05 14:13:15.952481+03	2	Entertainment - 3000.00 USD	3		12	1
49	2025-05-06 16:08:30.438283+03	6	Nails - 1000.00 KES	3		12	1
50	2025-05-07 10:02:49.819476+03	12	Salary - 25000.00	3		8	1
51	2025-05-07 10:02:50.259734+03	11	Salary - 25000.00	3		8	1
52	2025-05-13 11:02:46.435789+03	75	Shawarma - 200.00	2	[]	7	1
53	2025-05-14 11:54:39.670238+03	3	Jazz	3		4	1
54	2025-05-14 11:54:40.13774+03	5	Jazzlas	3		4	1
55	2025-05-14 11:54:40.227756+03	4	Test	3		4	1
56	2025-05-14 11:54:40.357566+03	2	systemupate	3		4	1
57	2025-05-14 12:00:58.061079+03	6	systemupate	3		4	1
58	2025-05-14 21:45:26.516253+03	8	First2	3		4	1
59	2025-05-14 21:46:37.475663+03	9	First3	3		4	1
60	2025-05-19 11:15:22.595911+03	1	systemupate	1	[{"added": {}}]	9	1
61	2025-05-19 12:33:36.33362+03	11	Ethan	2	[{"changed": {"fields": ["Email address"]}}]	4	1
62	2025-05-19 12:35:22.847369+03	11	Ethan	3		4	1
63	2025-06-11 11:15:15.320849+03	22	Investment - 2500.00	3		8	1
64	2025-06-11 11:15:15.457422+03	21	Salary - 2500.00	3		8	1
65	2025-06-11 11:15:15.488915+03	20	Salary - 20000.00	3		8	1
66	2025-06-11 11:15:15.530981+03	19	Salary - 20000.00	3		8	1
67	2025-06-11 11:15:15.686666+03	18	Other - 2500.00	3		8	1
68	2025-06-11 11:15:15.733107+03	17	Investment - 15000.00	3		8	1
69	2025-06-11 11:15:15.775527+03	1	iddek - 50000.00	3		8	1
70	2025-06-11 11:51:30.024024+03	91	FARE - 500.00	3		7	1
71	2025-06-11 11:51:31.759214+03	90	Ease Tech - 2001.00	3		7	1
72	2025-06-11 11:51:31.893127+03	89	Ease Tech - 2001.00	3		7	1
73	2025-06-11 11:51:32.302536+03	88	Ease Tech - 5100.00	3		7	1
74	2025-06-11 11:51:32.39265+03	87	Transport - 5100.00	3		7	1
75	2025-06-11 11:51:32.47029+03	78	Dun - 5100.00	3		7	1
76	2025-06-11 11:51:32.581417+03	76	Shawarma - 200.00	3		7	1
77	2025-06-11 11:51:32.669078+03	73	Nails - 1000.00	3		7	1
78	2025-06-11 11:51:32.855885+03	72	Nails - 1000.00	3		7	1
79	2025-06-11 11:51:32.951164+03	71	Payment - 2500.00	3		7	1
80	2025-06-11 11:51:33.037683+03	68	Nails - 1000.00	3		7	1
81	2025-06-11 11:51:33.114718+03	63	Dunda - 3000.00	3		7	1
82	2025-06-11 11:51:33.410933+03	50	Clothes - 2500.00	3		7	1
83	2025-06-11 11:51:33.5245+03	37	Food - 330.00	3		7	1
84	2025-06-11 11:51:33.627294+03	31	Shoes - 1800.00	3		7	1
85	2025-06-11 11:51:33.726869+03	25	TestingSS - 20.00	3		7	1
86	2025-06-11 11:51:33.980488+03	24	Testing - 10.00	3		7	1
87	2025-07-01 22:00:55.091633+03	12	Ethan	3		4	1
88	2025-07-01 22:00:55.277907+03	13	tee	3		4	1
89	2025-07-01 22:01:10.937685+03	10	First2	3		4	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	expenses	expensemanagement
8	expenses	incomemanagement
9	expenses	userauthentication
10	expenses	userprofile
11	expenses	expensereport
12	expenses	budget
13	expenses	monthlyexpensereport
14	django_celery_beat	crontabschedule
15	django_celery_beat	intervalschedule
16	django_celery_beat	periodictask
17	django_celery_beat	periodictasks
18	django_celery_beat	solarschedule
19	django_celery_beat	clockedschedule
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-28 19:39:03.644174+03
2	auth	0001_initial	2025-04-28 19:39:08.065806+03
3	admin	0001_initial	2025-04-28 19:39:09.198887+03
4	admin	0002_logentry_remove_auto_add	2025-04-28 19:39:09.27204+03
5	admin	0003_logentry_add_action_flag_choices	2025-04-28 19:39:09.319291+03
6	contenttypes	0002_remove_content_type_name	2025-04-28 19:39:09.482145+03
7	auth	0002_alter_permission_name_max_length	2025-04-28 19:39:09.738622+03
8	auth	0003_alter_user_email_max_length	2025-04-28 19:39:09.955471+03
9	auth	0004_alter_user_username_opts	2025-04-28 19:39:10.000361+03
10	auth	0005_alter_user_last_login_null	2025-04-28 19:39:10.050146+03
11	auth	0006_require_contenttypes_0002	2025-04-28 19:39:10.091995+03
12	auth	0007_alter_validators_add_error_messages	2025-04-28 19:39:10.138919+03
13	auth	0008_alter_user_username_max_length	2025-04-28 19:39:10.584462+03
14	auth	0009_alter_user_last_name_max_length	2025-04-28 19:39:10.658721+03
15	auth	0010_alter_group_name_max_length	2025-04-28 19:39:10.702274+03
16	auth	0011_update_proxy_permissions	2025-04-28 19:39:10.841451+03
17	auth	0012_alter_user_first_name_max_length	2025-04-28 19:39:10.986201+03
18	expenses	0001_initial	2025-04-28 19:39:12.257233+03
19	expenses	0002_expensemanagement_incomemanagement_and_more	2025-04-28 19:39:14.864843+03
20	sessions	0001_initial	2025-04-28 19:39:15.682875+03
21	expenses	0003_expensemanagement_currency_incomemanagement_currency_and_more	2025-04-28 20:54:37.799806+03
22	expenses	0004_alter_expensemanagement_user	2025-04-28 21:05:51.430441+03
23	expenses	0005_remove_budget_date_budget_currency_and_more	2025-04-29 12:43:46.199959+03
24	expenses	0006_alter_budget_currency	2025-04-29 12:48:04.330089+03
25	expenses	0007_expensemanagement_status	2025-04-29 14:47:27.954525+03
26	expenses	0008_monthlyexpensereport	2025-04-29 20:23:34.192386+03
27	expenses	0009_remove_expensemanagement_status	2025-04-30 14:31:29.044739+03
28	expenses	0010_expensemanagement_status	2025-04-30 15:06:14.588942+03
29	expenses	0011_alter_expensemanagement_status	2025-04-30 15:13:17.676177+03
30	expenses	0012_alter_expensemanagement_status	2025-04-30 15:21:51.234452+03
31	expenses	0013_alter_expensemanagement_status	2025-04-30 15:47:04.035954+03
32	expenses	0014_remove_expensemanagement_currency_and_more	2025-05-05 11:15:56.530022+03
33	expenses	0015_expensemanagement_timestamp	2025-05-05 18:26:09.089972+03
34	expenses	0016_rename_date_created_budget_created_at_and_more	2025-05-06 15:20:28.647911+03
35	expenses	0017_expensemanagement_status	2025-05-12 21:53:22.184004+03
36	expenses	0018_remove_budget_created_at_budget_alert_sent_and_more	2025-05-13 12:34:05.765569+03
37	expenses	0019_budget_half_alert_sent	2025-05-19 12:06:33.088313+03
38	expenses	0020_budget_date_created	2025-06-03 12:34:48.269286+03
39	django_celery_beat	0001_initial	2025-07-01 21:47:02.467971+03
40	django_celery_beat	0002_auto_20161118_0346	2025-07-01 21:47:02.987535+03
41	django_celery_beat	0003_auto_20161209_0049	2025-07-01 21:47:03.142112+03
42	django_celery_beat	0004_auto_20170221_0000	2025-07-01 21:47:03.330866+03
43	django_celery_beat	0005_add_solarschedule_events_choices	2025-07-01 21:47:03.468238+03
44	django_celery_beat	0006_auto_20180322_0932	2025-07-01 21:47:03.964515+03
45	django_celery_beat	0007_auto_20180521_0826	2025-07-01 21:47:04.06801+03
46	django_celery_beat	0008_auto_20180914_1922	2025-07-01 21:47:04.148511+03
47	django_celery_beat	0006_auto_20180210_1226	2025-07-01 21:47:04.339233+03
48	django_celery_beat	0006_periodictask_priority	2025-07-01 21:47:04.48274+03
49	django_celery_beat	0009_periodictask_headers	2025-07-01 21:47:04.591897+03
50	django_celery_beat	0010_auto_20190429_0326	2025-07-01 21:47:04.922572+03
51	django_celery_beat	0011_auto_20190508_0153	2025-07-01 21:47:05.386044+03
52	django_celery_beat	0012_periodictask_expire_seconds	2025-07-01 21:47:05.462594+03
53	django_celery_beat	0013_auto_20200609_0727	2025-07-01 21:47:05.627387+03
54	django_celery_beat	0014_remove_clockedschedule_enabled	2025-07-01 21:47:05.674491+03
55	django_celery_beat	0015_edit_solarschedule_events_choices	2025-07-01 21:47:05.72049+03
56	django_celery_beat	0016_alter_crontabschedule_timezone	2025-07-01 21:47:05.766567+03
57	django_celery_beat	0017_alter_crontabschedule_month_of_year	2025-07-01 21:47:05.840542+03
58	django_celery_beat	0018_improve_crontab_helptext	2025-07-01 21:47:05.899723+03
59	django_celery_beat	0019_alter_periodictasks_options	2025-07-01 21:47:05.955648+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
97uc8nnifufau36h8tthk236ct2of5xy	.eJxVjMsOwiAQRf-FtSFTyqO4dO83kGEYpGogKe3K-O_apAvd3nPOfYmA21rC1nkJcxJnocTpd4tID647SHestyap1XWZo9wVedAury3x83K4fwcFe_nWGgejjZ7IIZGxTik0ANpah5Fx8HbMDKMCBKPZueiYKSsNNpOfiL14fwDIqzee:1uCO81:1Dqc4y0vcwPAy50kehAt28_E4tk0-E5WaMVX7UiAzg8	2025-05-20 22:38:57.307611+03
na02op9q2bejdgjm5jylyxrqotzb8t7h	.eJxVjMsOwiAQRf-FtSE8igWX7vsNZIYZpGogKe3K-O_apAvd3nPOfYkI21ri1nmJM4mL0OL0uyGkB9cd0B3qrcnU6rrMKHdFHrTLqRE_r4f7d1Cgl2-dQ7KMgzagrDuP5DNTQGKVNGMGP9jRJcwZNDtLwfkQSBMiGhyUySjeHxLPOU8:1uThr9:ovlCnvc1_UYh3C28WCjLOGzrN1DAynWkSdi_wDt5_Mo	2025-07-07 17:09:07.199523+03
loxp7bi7sfhuteytk89hppo504531k03	.eJxVjMsOwiAQRf-FtSE8igWX7vsNZIYZpGogKe3K-O_apAvd3nPOfYkI21ri1nmJM4mL0OL0uyGkB9cd0B3qrcnU6rrMKHdFHrTLqRE_r4f7d1Cgl2-dQ7KMgzagrDuP5DNTQGKVNGMGP9jRJcwZNDtLwfkQSBMiGhyUySjeHxLPOU8:1uWW0Y:5tb8kmSq8hOg656qSy8YHUtHEIl3vTVy0Vf2PJb8NYQ	2025-07-15 11:06:26.60296+03
qw2qu3fprzhjm1k8wuqwkmx3eb2mzdjp	.eJxVjMsOwiAQRf-FtSE8igWX7vsNZIYZpGogKe3K-O_apAvd3nPOfYkI21ri1nmJM4mL0OL0uyGkB9cd0B3qrcnU6rrMKHdFHrTLqRE_r4f7d1Cgl2-dQ7KMgzagrDuP5DNTQGKVNGMGP9jRJcwZNDtLwfkQSBMiGhyUySjeHxLPOU8:1uZ76N:vabTT8Ok0_pTFUs44MqxqGUEdguX3h6Krxzp5VkVLS0	2025-07-22 15:07:11.550647+03
\.


--
-- Data for Name: expenses_budget; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_budget (id, category, budgeted_amount, user_id, currency, alert_sent, half_alert_sent, date_created) FROM stdin;
9	Utilities	15000.00	1	KES	f	f	2025-06-03
4	Food	330.00	1	KES	f	t	2025-06-03
5	Entertainment	4000.00	1	KES	t	t	2025-06-03
19	Food	2000.00	1	KES	f	f	2025-06-11
20	Other	5000.00	1	KES	f	t	2025-06-11
21	Other	10000.00	1	KES	f	t	2025-06-17
22	Food	2000.00	1	KES	f	f	2025-06-17
23	Food	3000.00	1	KES	f	f	2025-06-17
24	Food	500.00	1	KES	f	t	2025-06-23
25	Food	200.00	7	KES	f	t	2025-06-30
26	Utilities	2500.00	1	KES	f	f	2025-07-01
27	Other	2500.00	1	KES	f	f	2025-07-02
\.


--
-- Data for Name: expenses_expensemanagement; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_expensemanagement (id, title, amount, category, date, description, user_id, "timestamp", status) FROM stdin;
92	Visor	330.00	Other	2025-06-10	\N	1	2025-06-11 11:16:11.840845+03	Approved
93	Watch	100.00	Other	2025-06-10	\N	1	2025-06-11 11:52:35.296783+03	Approved
94	Doll Shoes	500.00	Utilities	2025-06-10	\N	1	2025-06-11 11:54:55.791775+03	Approved
95	Barber Shop	500.00	Utilities	2025-06-10	\N	1	2025-06-11 11:55:50.702712+03	Approved
96	Loan	2000.00	Other	2025-06-10	\N	1	2025-06-11 11:56:34.877165+03	Approved
97	Naivas	1300.00	Utilities	2025-06-10	\N	1	2025-06-11 11:57:46.368585+03	Approved
98	Chari	330.00	Food	2025-06-10	\N	1	2025-06-11 11:58:11.362607+03	Approved
99	Emirates shoes	500.00	Utilities	2025-06-10	\N	1	2025-06-11 11:59:18.362939+03	Approved
100	Bike	250.00	Other	2025-06-10	\N	1	2025-06-17 10:40:17.931154+03	Pending
101	Airtime	70.00	Other	2025-06-12	\N	1	2025-06-17 10:42:01.94244+03	Pending
102	Showmax	300.00	Entertainment	2025-06-11	\N	1	2025-06-17 10:43:08.70425+03	Pending
113	Chris	150.00	Other	2025-06-16	\N	1	2025-06-17 10:57:16.659704+03	Approved
114	Mum Loan	2500.00	Other	2025-06-15	\N	1	2025-06-17 11:20:00.310045+03	Approved
112	Chris	780.00	Entertainment	2025-06-15	\N	1	2025-06-17 10:56:31.400655+03	Approved
111	Airtime	80.00	Other	2025-06-15	\N	1	2025-06-17 10:55:29.598415+03	Approved
108	Airtime	30.00	Other	2025-06-14	\N	1	2025-06-17 10:52:18.301301+03	Approved
110	Chari	330.00	Food	2025-06-14	\N	1	2025-06-17 10:53:53.834777+03	Approved
109	Goddie	500.00	TRANSPORT	2025-06-14	\N	1	2025-06-17 10:53:21.394225+03	Approved
103	Goddie	200.00	Other	2025-06-13	\N	1	2025-06-17 10:44:00.145613+03	Approved
104	Bread	100.00	Food	2025-06-13	\N	1	2025-06-17 10:44:23.937017+03	Approved
105	Conny	50.00	Other	2025-06-13	\N	1	2025-06-17 10:44:53.38675+03	Approved
106	Conny	700.00	Entertainment	2025-06-13	\N	1	2025-06-17 10:45:28.473417+03	Approved
107	Bike	250.00	TRANSPORT	2025-06-13	\N	1	2025-06-17 10:49:49.872899+03	Approved
115	Fries	250.00	Food	2025-06-30	\N	7	2025-06-30 16:11:05.525799+03	Pending
116	Pedicure	1500.00	Other	2025-07-01	\N	1	2025-07-02 10:47:04.58751+03	Pending
\.


--
-- Data for Name: expenses_expensereport; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_expensereport (id, report_date, total_expenses, total_income, net_savings, user_id) FROM stdin;
\.


--
-- Data for Name: expenses_incomemanagement; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_incomemanagement (id, source, amount, date, description, user_id, currency) FROM stdin;
23	Salary	20000.00	2025-06-10	\N	1	KES
24	Other	2500.00	2025-06-25	\N	1	KES
25	Other	200.00	2025-06-30	\N	7	KES
26	Salary	25000.00	2025-07-01	\N	1	KES
\.


--
-- Data for Name: expenses_monthlyexpensereport; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_monthlyexpensereport (id, report_date, total_expenses, total_income, net_savings, user_id) FROM stdin;
1	2025-04-29	300.00	20000.00	19700.00	1
\.


--
-- Data for Name: expenses_userauthentication; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_userauthentication (id, username, password, email) FROM stdin;
1	systemupate	1234	cecinbarasa@gmail.com
\.


--
-- Data for Name: expenses_userprofile; Type: TABLE DATA; Schema: public; Owner: nabalayo
--

COPY public.expenses_userprofile (id, profile_picture, bio, date_of_birth, user_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 13, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 89, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 59, true);


--
-- Name: expenses_budget_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_budget_id_seq', 27, true);


--
-- Name: expenses_expensemanagement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_expensemanagement_id_seq', 116, true);


--
-- Name: expenses_expensereport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_expensereport_id_seq', 1, false);


--
-- Name: expenses_incomemanagement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_incomemanagement_id_seq', 26, true);


--
-- Name: expenses_monthlyexpensereport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_monthlyexpensereport_id_seq', 1, true);


--
-- Name: expenses_userauthentication_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_userauthentication_id_seq', 1, true);


--
-- Name: expenses_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nabalayo
--

SELECT pg_catalog.setval('public.expenses_userprofile_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: expenses_budget expenses_budget_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_budget
    ADD CONSTRAINT expenses_budget_pkey PRIMARY KEY (id);


--
-- Name: expenses_expensemanagement expenses_expensemanagement_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_expensemanagement
    ADD CONSTRAINT expenses_expensemanagement_pkey PRIMARY KEY (id);


--
-- Name: expenses_expensereport expenses_expensereport_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_expensereport
    ADD CONSTRAINT expenses_expensereport_pkey PRIMARY KEY (id);


--
-- Name: expenses_incomemanagement expenses_incomemanagement_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_incomemanagement
    ADD CONSTRAINT expenses_incomemanagement_pkey PRIMARY KEY (id);


--
-- Name: expenses_monthlyexpensereport expenses_monthlyexpensereport_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_monthlyexpensereport
    ADD CONSTRAINT expenses_monthlyexpensereport_pkey PRIMARY KEY (id);


--
-- Name: expenses_userauthentication expenses_userauthentication_email_key; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_userauthentication
    ADD CONSTRAINT expenses_userauthentication_email_key UNIQUE (email);


--
-- Name: expenses_userauthentication expenses_userauthentication_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_userauthentication
    ADD CONSTRAINT expenses_userauthentication_pkey PRIMARY KEY (id);


--
-- Name: expenses_userauthentication expenses_userauthentication_username_key; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_userauthentication
    ADD CONSTRAINT expenses_userauthentication_username_key UNIQUE (username);


--
-- Name: expenses_userprofile expenses_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_userprofile
    ADD CONSTRAINT expenses_userprofile_pkey PRIMARY KEY (id);


--
-- Name: expenses_userprofile expenses_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_userprofile
    ADD CONSTRAINT expenses_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: expenses_budget_user_id_3e911567; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_budget_user_id_3e911567 ON public.expenses_budget USING btree (user_id);


--
-- Name: expenses_expensemanagement_user_id_4f93b397; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_expensemanagement_user_id_4f93b397 ON public.expenses_expensemanagement USING btree (user_id);


--
-- Name: expenses_expensereport_user_id_61085961; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_expensereport_user_id_61085961 ON public.expenses_expensereport USING btree (user_id);


--
-- Name: expenses_incomemanagement_user_id_2fa4cd01; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_incomemanagement_user_id_2fa4cd01 ON public.expenses_incomemanagement USING btree (user_id);


--
-- Name: expenses_monthlyexpensereport_user_id_0407f2fd; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_monthlyexpensereport_user_id_0407f2fd ON public.expenses_monthlyexpensereport USING btree (user_id);


--
-- Name: expenses_userauthentication_email_5989c6f6_like; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_userauthentication_email_5989c6f6_like ON public.expenses_userauthentication USING btree (email varchar_pattern_ops);


--
-- Name: expenses_userauthentication_username_ad28ea72_like; Type: INDEX; Schema: public; Owner: nabalayo
--

CREATE INDEX expenses_userauthentication_username_ad28ea72_like ON public.expenses_userauthentication USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expenses_budget expenses_budget_user_id_3e911567_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_budget
    ADD CONSTRAINT expenses_budget_user_id_3e911567_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expenses_expensemanagement expenses_expensemanagement_user_id_4f93b397_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_expensemanagement
    ADD CONSTRAINT expenses_expensemanagement_user_id_4f93b397_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expenses_expensereport expenses_expensereport_user_id_61085961_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_expensereport
    ADD CONSTRAINT expenses_expensereport_user_id_61085961_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expenses_incomemanagement expenses_incomemanagement_user_id_2fa4cd01_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_incomemanagement
    ADD CONSTRAINT expenses_incomemanagement_user_id_2fa4cd01_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expenses_monthlyexpensereport expenses_monthlyexpensereport_user_id_0407f2fd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_monthlyexpensereport
    ADD CONSTRAINT expenses_monthlyexpensereport_user_id_0407f2fd_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expenses_userprofile expenses_userprofile_user_id_593b8cab_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nabalayo
--

ALTER TABLE ONLY public.expenses_userprofile
    ADD CONSTRAINT expenses_userprofile_user_id_593b8cab_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

