# Generated by Django 4.2.20 on 2025-04-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0002_expensemanagement_incomemanagement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensemanagement",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("KES", "Kenyan Shilling"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("AUD", "Australian Dollar"),
                    ("CAD", "Canadian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("CNY", "Chinese Yuan"),
                    ("NZD", "New Zealand Dollar"),
                    ("ZAR", "South African Rand"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("MXN", "Mexican Peso"),
                ],
                default="KES",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="incomemanagement",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("KES", "Kenyan Shilling"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("AUD", "Australian Dollar"),
                    ("CAD", "Canadian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("CNY", "Chinese Yuan"),
                    ("NZD", "New Zealand Dollar"),
                    ("ZAR", "South African Rand"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("MXN", "Mexican Peso"),
                ],
                default="KES",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_savings", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
