# Generated by Django 4.2.20 on 2025-04-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "expenses",
            "0003_expensemanagement_currency_incomemanagement_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensemanagement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
