# Generated by Django 4.2.20 on 2025-04-29 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_expensemanagement_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="date",
        ),
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="budget",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budget",
            name="actual_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
