# Generated by Django 4.2.20 on 2025-04-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_remove_budget_date_budget_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("KES", "Kenyan Shilling"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("AUD", "Australian Dollar"),
                    ("CAD", "Canadian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("CNY", "Chinese Yuan"),
                    ("NZD", "New Zealand Dollar"),
                    ("ZAR", "South African Rand"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("MXN", "Mexican Peso"),
                ],
                default="KES",
                max_length=3,
            ),
        ),
    ]
