# Generated by Django 4.2.20 on 2025-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_alter_budget_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensemanagement",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
