# Generated by Django 4.2.20 on 2025-04-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_monthlyexpensereport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensemanagement",
            name="status",
        ),
    ]
