# Generated by Django 4.2.20 on 2025-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0009_remove_expensemanagement_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensemanagement",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
