# Generated by Django 4.2.20 on 2025-04-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0011_alter_expensemanagement_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensemanagement",
            name="status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("PENDING", "Pending")],
                default="PAID",
                max_length=20,
            ),
        ),
    ]
