# Generated by Django 4.2.20 on 2025-05-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0013_alter_expensemanagement_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensemanagement",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="expensemanagement",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="expensemanagement",
            name="status",
        ),
        migrations.AlterField(
            model_name="expensemanagement",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="expensemanagement",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="expensemanagement",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
