# Generated by Django 4.2.20 on 2025-05-05 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0014_remove_expensemanagement_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensemanagement",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
