# Generated by Django 4.2.20 on 2025-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0015_expensemanagement_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="actual_amount",
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="budget",
            name="currency",
            field=models.CharField(max_length=10),
        ),
    ]
