# Generated by Django 4.2.20 on 2025-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0018_remove_budget_created_at_budget_alert_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="half_alert_sent",
            field=models.BooleanField(default=False),
        ),
    ]
