# Generated by Django 4.2.20 on 2025-06-03 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0019_budget_half_alert_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
